### ISSUE TITLE
Create new repo: elastic-agent-inputs

### ISSUE THREAD

**Issue by kvch** [elastic/elastic-agent-inputs#2]
The goal of the issue is to prepare a repository for developers to contribute to.

### TODO
- [x] Create a new repository named elastic-agent-inputs
- [x] Transfer tickets from the meta ticket to the new repo
- [x] Add licence
- [x] Add CHANGELOG
- [x] Add the new repo to the CI
   - [x] add access to @elasticmachine  
   - [x] run onboarder job: https://beats-ci.elastic.co/job/robots/job/onboarding-ci-pipeline/
- [x] Run linter from elastic-agent-libs (example: https://github.com/elastic/beats/pull/30896 https://github.com/elastic/beats/pull/30985)
- [x] Enable robots automation for labels creation

**Comment by kvch** [comment]
The repo is ready for development.
